# -*- ruby -*-

require './../glib2/lib/gnome2-raketask'

package = GNOME2Package.new do |_package|
  _package.summary = "Ruby/GtkSourceView2 is a Ruby binding of gtksourceview-2.x."
  _package.description = "Ruby/GtkSourceView2 is a Ruby binding of gtksourceview-2.x."
  _package.dependency.gem.runtime = ["gtk2"]
  _package.win32.packages = []
  _package.win32.dependencies = []
  _package.post_install_message = "This library is experimental."
end
package.define_tasks

