# -*- ruby -*-

$LOAD_PATH.unshift("./../glib2/lib")
require 'gnome2/rake/package-task'

package_task = GNOME2::Rake::PackageTask.new do |package|
  package.summary = "Ruby/GtkSourceView2 is a Ruby binding of gtksourceview-2.x."
  package.description = "Ruby/GtkSourceView2 is a Ruby binding of gtksourceview-2.x."
  package.dependency.gem.runtime = ["gtk2"]
  package.windows.packages = ["gtksourceview"]
  package.windows.dependencies = ["libxml2"]
end
package_task.define
