extern void   Init_atk_action();
extern void   Init_atk_component();
extern void   Init_atk_document();
extern void   Init_atk_editabletext();
extern void   Init_atk_gobjectaccessible();
extern void   Init_atk_hyperlink();
extern void   Init_atk_hypertext();
extern void   Init_atk_image();
extern void   Init_atk_implementor();
extern void   Init_atk_noopobject();
extern void   Init_atk_noopobjectfactory();
extern void   Init_atk_object();
extern void   Init_atk_objectfactory();
extern void   Init_atk_registry();
extern void   Init_atk_relation();
extern void   Init_atk_relation_set();
extern void   Init_atk_selection();
extern void   Init_atk_state();
extern void   Init_atk_state_set();
extern void   Init_atk_streamable_content();
extern void   Init_atk_table();
extern void   Init_atk_text();
extern void   Init_atk_text_range();
extern void   Init_atk_text_rectangle();
extern void   Init_atk_util();
extern void   Init_atk_value();
void Init_atk_inits()
{
   Init_atk_action();
   Init_atk_component();
   Init_atk_document();
   Init_atk_editabletext();
   Init_atk_gobjectaccessible();
   Init_atk_hyperlink();
   Init_atk_hypertext();
   Init_atk_image();
   Init_atk_implementor();
   Init_atk_noopobject();
   Init_atk_noopobjectfactory();
   Init_atk_object();
   Init_atk_objectfactory();
   Init_atk_registry();
   Init_atk_relation();
   Init_atk_relation_set();
   Init_atk_selection();
   Init_atk_state();
   Init_atk_state_set();
   Init_atk_streamable_content();
   Init_atk_table();
   Init_atk_text();
   Init_atk_text_range();
   Init_atk_text_rectangle();
   Init_atk_util();
   Init_atk_value();
}
