# -*- ruby -*-

$LOAD_PATH.unshift("./../glib2/lib")
require 'gnome2/rake/package-task'

package_task = GNOME2::Rake::PackageTask.new do |package|
  package.summary = "Ruby/VTE is a Ruby binding of VTE."
  package.description = "Ruby/VTE is a Ruby binding of VTE."
  package.dependency.gem.runtime = ["gtk2"]
  package.windows.packages = []
  package.windows.dependencies = []
end
package_task.define

