# -*- ruby -*-

require './../glib2/lib/gnome2-raketask'

package = GNOME2Package.new do |_package|
  _package.summary = "Ruby/VTE is a Ruby binding of VTE."
  _package.description = "Ruby/VTE is a Ruby binding of VTE."
  _package.dependency.gem.runtime = ["gtk2"]
  _package.win32.packages = []
  _package.win32.dependencies = []
end
package.define_tasks

