# -*- ruby -*-

$LOAD_PATH.unshift("./../glib2/lib")
require "gnome2/rake/package-task"

package_task = GNOME2::Rake::PackageTask.new do |package|
  package.summary = "Ruby/Pango is a Ruby binding of pango-1.x."
  package.description = "Ruby/Pango is a Ruby binding of pango-1.x."
  package.dependency.gem.runtime = [["cairo", ">= 1.10.0"], "glib2"]
  package.windows.packages = []
  package.windows.dependencies = []
  package.windows.build_dependencies = ["glib2", "gobject-introspection"]
  package.external_packages = [
    {
      :name => "pango",
      :download_site => :gnome,
      :label => "pango",
      :version => "1.34.0",
      :compression_method => "xz",
      :windows => {
        :configure_args => [
          "--enable-introspection",
        ],
      },
    }
  ]
end
package_task.define

