# -*- ruby -*-
#
# Copyright (C) 2011-2015  Ruby-GNOME2 Project Team
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

$LOAD_PATH.unshift("./../glib2/lib")
require "gnome2/rake/package-task"

package_task = GNOME2::Rake::PackageTask.new do |package|
  package.summary = "Ruby/Pango is a Ruby binding of pango-1.x."
  package.description = "Ruby/Pango is a Ruby binding of pango-1.x."
  package.dependency.gem.runtime = [["cairo", ">= 1.14.0"], "glib2"]
  package.windows.packages = []
  package.windows.dependencies = []
  package.windows.build_dependencies = ["glib2", "gobject-introspection"]
  package.external_packages = [
    {
      :name => "icu",
      :download_base_url => "http://download.icu-project.org/files/icu4c/55.1",
      :label => "gobject-introspection",
      :base_name => "icu",
      :archive_base_name => "icu4c-55_1-src.tgz",
      :compression_method => "gz",
      :base_dir_in_package => "source",
      :windows => {
        :configure_args => [
          "--with-cross-build=#{package.package.tmp_dir}/native/icu/icu/source",
        ],
        :built_file => "bin/icu-config",
      },
      :native => {
        :build => true,
        :built_file => "bin/icu-config",
      },
    },
    {
      :name => "harfbuzz",
      :download_base_url => "http://www.freedesktop.org/software/harfbuzz/release",
      :label => "HarfBuzz",
      :version => "1.0.3",
      :compression_method => "bz2",
      :windows => {
        :configure_args => [
        ],
        :patches => [
        ],
        :built_file => "bin/libharfbuzz-0.dll",
      },
    },
    {
      :name => "pango",
      :download_site => :gnome,
      :label => "pango",
      :version => "1.36.8",
      :compression_method => "xz",
      :windows => {
        :configure_args => [
          "--enable-introspection",
        ],
        :patches => [
          "pango-1.34.0-enable-fc-font.diff",
        ],
        :built_file => "bin/libpango-1.0-0.dll",
      },
    },
  ]
end
package_task.define
