# -*- ruby -*-
#
# Copyright (C) 2012  Ruby-GNOME2 Project Team
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

$LOAD_PATH.unshift("./../glib2/lib")
require "gnome2-raketask"

package = GNOME2Package.new do |_package|
  _package.summary = "Ruby/GObjectIntrospection is a Ruby binding of GObjectIntrospection."
  _package.description = "Ruby/GObjectIntrospection is a Ruby binding of GObjectIntrospection."
  _package.dependency.gem.runtime = ["glib2"]
  _package.dependency.gem.development = [["test-unit", ">= 2"]]
  _package.win32.packages = []
  _package.win32.dependencies = []
  _package.win32.build_dependencies = ["glib2"]
  _package.win32.build_packages = [
    {
      :name => "gobject-introspection",
      :download_site => :gnome,
      :label => "gobject-introspection",
      :version => "1.35.3",
      :configure_args => [],
      :compression_method => "xz",
    },
  ]
end
package.define_tasks
