# -*- ruby -*-
#
# Copyright (C) 2013  Ruby-GNOME2 Project Team
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

$LOAD_PATH.unshift("./../glib2/lib")
require "gnome2/rake/package-task"

package_task = GNOME2::Rake::PackageTask.new do |package|
  package.summary = "Ruby/WebKitGTK is a Ruby binding of WebKitGTK+."
  package.description = "Ruby/WebKitGTK is a Ruby binding of WebKitGTK+."
  package.dependency.gem.runtime = ["gobject-introspection", "gtk3"]
  package.dependency.gem.development = ["test-unit-notify"]
  package.windows.packages = []
  package.windows.dependencies = []
  package.windows.build_dependencies = ["glib2", "gobject-introspection"]
  package.external_packages = [
    {
      :name => "webkitgtk",
      :download_base_url => "http://webkitgtk.org/releases",
      :label => "WebKitGTK+",
      :version => "2.0.0",
      :compression_method => "xz",
      :windows => {
        :configure_args => [
          "--enable-introspection",
        ],
      },
    },
  ]
end
package_task.define

namespace :dependency do
  desc "Install depenencies"
  task :install do
    # TODO: Install gir1.2-webkit-3.0 on Debian.
  end
end

task :build => "dependency:install"
