# -*- ruby -*-
#
# Copyright (C) 2016  Ruby-GNOME2 Project Team
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

$LOAD_PATH.unshift("./../glib2/lib")
require 'gnome2/rake/package-task'

package_task = GNOME2::Rake::PackageTask.new do |package|
  package.summary = "Ruby/Gnumeric is a Ruby binding of Gnumeric."
  package.description = "Ruby/Gnumeric is a Ruby binding of Gnumeric."
  package.dependency.gem.runtime = ["goffice", "gobject-introspection"]
  package.windows.packages = []
  package.windows.dependencies = ["libxml2"]
  package.windows.build_dependencies = [
    "goffice",
    "gobject-introspection",
  ]
  package.windows.gobject_introspection_dependencies = [
    "gio2"
  ]
  package.external_packages = [
    {
      :name => "gnumeric",
      :download_site => :gnome,
      :label => "gnumeric",
      :version => "1.12.35",
      :compression_method => "xz",
      :windows => {
        :configure_args => [
        ],
        :patches => [
        ]
      },
    },
  ]
end
package_task.define
