# Copyright (C) 2017  Ruby-GNOME2 Project Team
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

# Copyright (C) 2017  Ruby-GNOME2 Project Team
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

require "pkg-config"
require "native-package-installer"

if File.exist?(File.join(__dir__, "..", "vendor"))
  task :default => "nothing"
else
  task :default => "dependency:check"
end

task :nothing do
end

namespace :dependency do
  desc "Check dependency"
  task :check do
    unless PKGConfig.check_version?("libgoffice-0.10")
      goffice010_spec = {
        :debian => "libgoffice-0.10-dev",
        :homebrew => "goffice",
      }
      unless NativePackageInstaller.install(goffice010_spec)
        unless PKGConfig.check_version?("libgoffice-0.8")
          goffice08_spec = {
            :debian => "libgoffice-0.8-dev",
            :redhat => "goffice08-devel",
            :homebrew => "goffice",
          }
          unless NativePackageInstaller.install(goffice08_spec)
            exit(false)
          end
        end
      end
    end
  end
end
