#!/usr/bin/env ruby
=begin
  l10n_gui.rb - Ruby/Libglade2 sample script.

  This sample is auto-generated by ruby-glade-create-template
  except header part ;). 

  Usually, YOU DON'T NEED TOUCH THIS.

  Copyright (c) 2004 Ruby-GNOME2 Project
  This program is licenced under the same licence as Ruby-GNOME2.

  $Id: l10n_gui.rb,v 1.1 2004/07/11 15:09:28 mutoh Exp $
=end

#!/usr/bin/env ruby
require 'libglade2'
class L10n
  def initialize(path_or_data, root = nil, domain = nil, localedir = nil, flag = GladeXML::FILE)
    @glade = GladeXML.new(path_or_data, root, domain, localedir, flag) {|handler| method(handler)}
  end
  def on_hello_button_clicked(widget)
    puts "on_hello_button_clicked() is not implemented yet."
  end
  def on_window1_destroy_event(widget, arg0)
    puts "on_window1_destroy_event() is not implemented yet."
  end
  def on_exit_button_clicked(widget)
    puts "on_exit_button_clicked() is not implemented yet."
  end
end

if __FILE__ == $0
  # Set values as your own application. 
  PROG_PATH = "l10n.glade"
  PROG_NAME = "YOUR_APPLICATION_NAME"
  Gtk.init
  L10n.new(PROG_PATH, nil, PROG_NAME)
  Gtk.main
end
