# -*- ruby -*-

$LOAD_PATH.unshift("./../glib2/lib")
require 'gnome2-raketask'

package = GNOME2Package.new do |_package|
  _package.summary = "Ruby/GtkSourceView3 is a Ruby binding of gtksourceview-3.x."
  _package.description = "Ruby/GtkSourceView3 is a Ruby binding of gtksourceview-3.x."
  _package.dependency.gem.runtime = ["gtk3"]
  _package.win32.packages = []
  _package.win32.dependencies = ["libxml2"]
  _package.win32.build_dependencies = [
    "glib2", "atk", "pango", "gdk_pixbuf2", "gdk3",
  ]
  _package.win32.build_packages = [
    {
      :name => "gtksourceview",
      :download_site => :gnome,
      :label => "GtkSourceView",
      :version => "3.6.3",
      :configure_args => [],
      :compression_method => "xz",
    }
  ]
  _package.required_ruby_version = ">= 1.9.2"
  _package.post_install_message = "This library is experimental."
end
package.define_tasks

