# -*- ruby -*-
#
# Copyright (C) 2012-2013  Ruby-GNOME2 Project Team
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

$LOAD_PATH.unshift("./../glib2/lib")
require "gnome2/rake/package-task"

package_task = GNOME2::Rake::PackageTask.new do |package|
  package.summary = "Ruby/GtkSourceView3 is a Ruby binding of gtksourceview-3.x."
  package.description = "Ruby/GtkSourceView3 is a Ruby binding of gtksourceview-3.x."
  package.dependency.gem.runtime = ["gtk3"]
  package.windows.packages = []
  package.windows.dependencies = ["libxml2"]
  package.windows.build_dependencies = [
    "glib2",
    "atk",
    "pango",
    "gdk_pixbuf2",
    "gdk3",
  ]
  package.external_packages = [
    {
      :name => "gtksourceview",
      :download_site => :gnome,
      :label => "GtkSourceView",
      :version => "3.6.3",
      :compression_method => "xz",
    }
  ]
end
package_task.define

