# -*- ruby -*-
#
# Copyright (C) 2016  Ruby-GNOME2 Project Team
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

$LOAD_PATH.unshift("./../glib2/lib")
require "gnome2/rake/package-task"

package_task = GNOME2::Rake::PackageTask.new do |package|
  package.summary =
    "Ruby/ClutterGDK is a Ruby binding of GDK specific API of Clutter."
  package.description =
    "Ruby/ClutterGDK is a Ruby binding of GDK specific API of Clutter."
  package.dependency.gem.runtime = ["clutter", "gdk3"]
  package.windows.packages = []
  package.windows.dependencies = []
  package.windows.build_dependencies = [
    "glib2",
    "atk",
    "pango",
    "gdk_pixbuf2",
    "gobject-introspection",
    "clutter",
    "gdk3",
  ]
  package.windows.gobject_introspection_dependencies = [
    "atk",
    "pango",
    "gdk_pixbuf2",
    "clutter",
    "gdk3",
  ]
  package.external_packages = [
    {
      :name => "clutter-gdk",
      :download_site => :gnome,
      :label => "Clutter-GTK",
      :version => "1.8.0",
      :compression_method => "xz",
      :windows => {
        :configure_args => [
          "--enable-introspection",
        ],
        :patches => [
        ],
        # :need_autoreconf => true,
        :built_file => "bin/libclutter-gdk-1.0-0.dll",
      },
    }
  ]
end
package_task.define

namespace :dependency do
  desc "Install depenencies"
  task :install do
  end
end

task :build => "dependency:install"
