# -*- ruby -*-
#
# Copyright (C) 2012  Ruby-GNOME2 Project Team
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

$LOAD_PATH.unshift("./../glib2/lib")
require "gnome2-raketask"

package = GNOME2Package.new do |_package|
  _package.summary = "Ruby/Clutter is a Ruby binding of Clutter."
  _package.description = "Ruby/Clutter is a Ruby binding of Clutter."
  _package.dependency.gem.runtime = ["cairo-gobject", "gobject-introspection"]
  _package.dependency.gem.development = ["test-unit-notify"]
  _package.win32.packages = []
  _package.win32.dependencies = []
  _package.win32.build_dependencies = ["glib2", "gobject-introspection"]
  _package.win32.build_packages = []
end
package.define_tasks

namespace :dependency do
  desc "Install depenencies"
  task :install do
    # TODO: Install gir1.2-clutter-1.0 on Debian.
  end
end

task :build => "dependency:install"
