# -*- ruby -*-

$LOAD_PATH.unshift("./../glib2/lib")
require "gnome2/rake/package-task"

package_task = GNOME2::Rake::PackageTask.new do |package|
  package.summary = "Ruby/GDK3 is a Ruby binding of GDK-3.x."
  package.description = "Ruby/GDK3 is a Ruby binding of GDK-3.x."
  package.dependency.gem.runtime = ["pango", "gdk_pixbuf2"]
  package.windows.packages = []
  package.windows.dependencies = []
  package.windows.build_dependencies = [
    "glib2",
    "atk",
    "pango",
    "gdk_pixbuf2",
    "gobject-introspection",
  ]
  package.windows.gobject_introspection_dependencies = [
    "atk",
    "pango",
    "gdk_pixbuf2",
  ]
  package.external_packages = [
    {
      :name => "gtk+",
      :download_site => :gnome,
      :label => "GTK+",
      :version => "3.10.6",
      :compression_method => "xz",
      :windows => {
        :configure_args => [
          "--enable-introspection",
          "--with-included-immodules=ime",
        ],
        :patches => [
          "gdk+-3.10.6-remove-def-use.diff",
        ],
        :need_autoreconf => true,
        :built_file => "bin/libgdk-3-0.dll",
      },
    },
    {
      :name => "hicolor-icon-theme",
      :download_base_url => "http://icon-theme.freedesktop.org/releases",
      :label => "gtk-hi-color-icon-theme",
      :version => "0.13",
      :windows => {
        :configure_args => [],
        :build_concurrently => false,
        :built_file => "share/icons/hicolor/index.theme",
      }
    },
  ]
end
package_task.define
