# -*- ruby -*-

$LOAD_PATH.unshift("./../glib2/lib")
require "gnome2/rake/package-task"

package_task = GNOME2::Rake::PackageTask.new do |package|
  package.summary = "Ruby/GDK3 is a Ruby binding of GDK-3.x."
  package.description = "Ruby/GDK3 is a Ruby binding of GDK-3.x."
  package.dependency.gem.runtime = ["atk", "pango", "gdk_pixbuf2"]
  package.windows.packages = []
  package.windows.dependencies = []
  package.windows.build_dependencies = [
    "glib2",
    "atk",
    "pango",
    "gdk_pixbuf2",
    "gobject-introspection",
  ]
  package.windows.gobject_introspection_dependencies = [
    "atk",
    "pango",
    "gdk_pixbuf2",
  ]
  package.external_packages = [
    {
      :name => "gtk+",
      :download_site => :gnome,
      :label => "GTK+",
      :version => "3.8.0",
      :compression_method => "xz",
      :windows => {
        :configure_args => [
          "--enable-introspection",
        ],
      },
    }
  ]
  package.required_ruby_version = ">= 1.9.2"
  package.post_install_message = "This library is experimental."
end
package_task.define
