# -*- ruby -*-
#
# Copyright (C) 2011-2018  Ruby-GNOME2 Project Team
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

$LOAD_PATH.unshift("./../glib2/lib")
require "gnome2/rake/package-task"

package_name = File.basename(__dir__)
spec = Gem::Specification.load("#{package_name}.gemspec")

GNOME2::Rake::PackageTask.define(spec, __dir__) do |package|
  package.windows.packages = []
  package.windows.dependencies = []
  package.windows.build_dependencies = [
    "glib2",
    "atk",
    "pango",
    "gdk_pixbuf2",
    "gobject-introspection",
  ]
  package.windows.gobject_introspection_dependencies = [
    "atk",
    "pango",
    "gdk_pixbuf2",
  ]
  package.external_packages = [
    {
      :name => "libepoxy",
      :download_site => :gnome,
      :label => "Epoxy",
      :version => "1.5.2",
      :compression_method => "xz",
      :windows => {
        :built_file => "bin/libepoxy-0.dll",
      },
    },
    {
      :name => "gtk+",
      :download_site => :gnome,
      :label => "GTK+",
      :version => "3.23.2",
      :compression_method => "xz",
      :windows => {
        :configure_args => [
          "--enable-introspection",
          "--with-included-immodules",
        ],
        :patches => [
        ],
        :need_autoreconf => true,
        :build_concurrently => false,
        :built_file => "bin/libgdk-3-0.dll",
      },
    },
    {
      :name => "hicolor-icon-theme",
      :download_base_url => "https://icon-theme.freedesktop.org/releases",
      :label => "gtk-hi-color-icon-theme",
      :version => "0.15",
      :compression_method => "xz",
      :windows => {
        :configure_args => [],
        :build_concurrently => false,
        :built_file => "share/icons/hicolor/index.theme",
      }
    },
    {
      :name => "adwaita-icon-theme",
      :download_site => :gnome,
      :label => "adwaita-icon-theme",
      :version => "3.28.0",
      :compression_method => "xz",
      :windows => {
        :use_gobject_introspection => false,
        :configure_args => [],
        :build_concurrently => false,
        :built_file => "share/icons/Adwaita/index.theme",
      }
    },
  ]
end
