# -*- ruby -*-

$LOAD_PATH.unshift("./../glib2/lib")
require 'gnome2/rake/package-task'

package_task = GNOME2::Rake::PackageTask.new do |package|
  package.summary = "Ruby/VLC is a Ruby binding of libVLC for Ruby/GTK."
  package.description = "Ruby/VLC is a Ruby binding of libVLC for Ruby/GTK."
  package.dependency.gem.runtime = ["glib2"]
  package.windows.packages = []
  package.windows.dependencies = []
  package.post_install_message = "This library is experimental."
end
package_task.define

