FROM ubuntu:14.04

RUN \
  apt update && \
  apt install -y \
    sudo \
    xvfb \
    git \
    wget \
    libssl-dev \
    libreadline-dev \
    libgirepository1.0-dev \
    gstreamer1.0-plugins-good \
    gir1.2-clutter-1.0 \
    gir1.2-clutter-gst-2.0 \
    gir1.2-gtkclutter-1.0 \
    gir1.2-gtksource-3.0 \
    gir1.2-vte-2.90 \
    gir1.2-webkit-3.0 \
    gir1.2-webkit2-3.0 \
    gir1.2-gsf-1 \
    gir1.2-goffice-0.10 \
    gir1.2-gnumeric \
    gnumeric \
    gnome-icon-theme \
    dbus-x11

RUN \
  useradd --user-group --create-home ruby-gnome2

RUN \
  echo "ruby-gnome2 ALL=(ALL:ALL) NOPASSWD:ALL" | \
    EDITOR=tee visudo -f /etc/sudoers.d/ruby-gnome2

USER ruby-gnome2

RUN \
  git clone --depth 1 https://github.com/rbenv/rbenv.git ~/.rbenv
RUN \
  git clone --depth 1 https://github.com/rbenv/ruby-build.git \
    ~/.rbenv/plugins/ruby-build

ENV PATH=/home/ruby-gnome2/.rbenv/shims:/home/ruby-gnome2/.rbenv/bin:$PATH
ENV RUBY_VERSION=2.4.1
RUN \
  rbenv install ${RUBY_VERSION}
RUN \
  rbenv global ${RUBY_VERSION}

COPY . /home/ruby-gnome2/ruby-gnome2
RUN sudo chown -R ruby-gnome2:ruby-gnome2 /home/ruby-gnome2/ruby-gnome2
WORKDIR /home/ruby-gnome2/ruby-gnome2

RUN gem install bundler
RUN bundle install

CMD [ \
  "xvfb-run", \
     "--server-args", "-screen 0 640x480x24", \
     "bundle", "exec", "rake" \
]
