FROM ubuntu:16.10

RUN \
  apt update && \
  apt install -y \
    sudo \
    ruby-dev \
    xvfb \
    libgirepository1.0-dev \
    gstreamer1.0-plugins-good \
    gir1.2-clutter-1.0 \
    gir1.2-clutter-gst-3.0 \
    gir1.2-gtkclutter-1.0 \
    gir1.2-gtksource-3.0 \
    gir1.2-vte-2.91 \
    gir1.2-webkit-3.0 \
    gir1.2-webkit2-4.0 \
    gir1.2-gsf-1 \
    gir1.2-goffice-0.10 \
    gir1.2-gnumeric \
    gnumeric \
    gnome-icon-theme \
    dbus-x11

RUN \
  gem install bundler

RUN \
  useradd --user-group --create-home ruby-gnome2

RUN \
  echo "ruby-gnome2 ALL=(ALL:ALL) NOPASSWD:ALL" | \
    EDITOR=tee visudo -f /etc/sudoers.d/ruby-gnome2

COPY . /home/ruby-gnome2/ruby-gnome2
RUN chown -R ruby-gnome2:ruby-gnome2 /home/ruby-gnome2/ruby-gnome2

USER ruby-gnome2
WORKDIR /home/ruby-gnome2/ruby-gnome2

RUN bundle install

CMD xvfb-run --server-args "-screen 0 640x480x24" bundle exec rake
