FROM ubuntu:16.04

RUN \
  apt update && \
  apt install -y \
    sudo \
    gcc \
    g++ \
    make \
    ruby-dev \
    xvfb \
    gstreamer1.0-plugins-good \
    gnumeric \
    gnome-icon-theme \
    dbus-x11

RUN \
  gem install bundler

RUN \
  useradd --user-group --create-home ruby-gnome

RUN \
  echo "ruby-gnome ALL=(ALL:ALL) NOPASSWD:ALL" | \
    EDITOR=tee visudo -f /etc/sudoers.d/ruby-gnome

COPY . /home/ruby-gnome/ruby-gnome
RUN chown -R ruby-gnome:ruby-gnome /home/ruby-gnome/ruby-gnome

USER ruby-gnome
WORKDIR /home/ruby-gnome/ruby-gnome

RUN bundle install --path vendor/bundle

CMD xvfb-run --server-args "-screen 0 640x480x24" bundle exec rake
