# -*- ruby -*-

$LOAD_PATH.unshift("./../glib2/lib")
require 'gnome2-raketask'

package = GNOME2Package.new do |_package|
  _package.summary = "Ruby/GdkPixbuf2 is a Ruby binding of GdkPixbuf-2.x."
  _package.description = "Ruby/GdkPixbuf2 is a Ruby binding of GdkPixbuf-2.x."
  _package.dependency.gem.runtime = ["glib2"]
  _package.win32.packages = []
  _package.win32.dependencies = ["zlib", "libpng"]
  _package.win32.build_dependencies = ["glib2"]
  _package.win32.build_packages = [
    {
      :name => "gdk-pixbuf",
      :download_site => :gnome,
      :label => "gdk-pixbuf",
      :version => "2.26.5",
      :configure_args => [],
      :compression_method => "xz",
      :need_autoreconf => true,
      :patches => [
        "gdk-pixbuf-2.26.5-add-missing-exeext.diff",
      ],
    }
  ]
end
package.define_tasks
