# -*- ruby -*-
#
# Copyright (C) 2011-2015  Ruby-GNOME2 Project Team
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

$LOAD_PATH.unshift("./../glib2/lib")
require "gnome2/rake/package-task"

package_task = GNOME2::Rake::PackageTask.new do |package|
  package.summary = "Ruby/GdkPixbuf2 is a Ruby binding of GdkPixbuf-2.x."
  package.description = "Ruby/GdkPixbuf2 is a Ruby binding of GdkPixbuf-2.x."
  package.dependency.gem.runtime = ["glib2"]
  package.windows.packages = []
  package.windows.dependencies = []
  package.windows.build_dependencies = [
    "glib2",
    "gobject-introspection",
  ]
  package.external_packages = [
    {
      :name => "gdk-pixbuf",
      :download_site => :gnome,
      :label => "gdk-pixbuf",
      :version => "2.30.8",
      :compression_method => "xz",
      :windows => {
        :configure_args => [
          "--with-included-loaders",
          "--enable-introspection",
        ],
        :build_concurrently => false,
        :built_file => "bin/libgdk_pixbuf-2.0-0.dll",
      },
    }
  ]
end
package_task.define
