
SHELL = /bin/sh

# V=0 quiet, V=1 verbose.  other values don't work.
V = 0
V0 = $(V:0=)
Q1 = $(V:1=)
Q = $(Q1:0=@)
ECHO1 = $(V:1=@ :)
ECHO = $(ECHO1:0=@ echo)
NULLCMD = :

#### Start of system configuration section. ####

srcdir = .
topdir = /home/thibault-vallois/.rbenv/versions/3.3.5/include/ruby-3.3.0
hdrdir = $(topdir)
arch_hdrdir = /home/thibault-vallois/.rbenv/versions/3.3.5/include/ruby-3.3.0/x86_64-linux
PATH_SEPARATOR = :
VPATH = $(srcdir):$(arch_hdrdir)/ruby:$(hdrdir)/ruby
prefix = $(DESTDIR)/home/thibault-vallois/.rbenv/versions/3.3.5
rubysitearchprefix = $(rubylibprefix)/$(sitearch)
rubyarchprefix = $(rubylibprefix)/$(arch)
rubylibprefix = $(libdir)/$(RUBY_BASE_NAME)
exec_prefix = $(prefix)
vendorarchhdrdir = $(vendorhdrdir)/$(sitearch)
sitearchhdrdir = $(sitehdrdir)/$(sitearch)
rubyarchhdrdir = $(rubyhdrdir)/$(arch)
vendorhdrdir = $(rubyhdrdir)/vendor_ruby
sitehdrdir = $(rubyhdrdir)/site_ruby
rubyhdrdir = $(includedir)/$(RUBY_VERSION_NAME)
vendorarchdir = $(vendorlibdir)/$(sitearch)
vendorlibdir = $(vendordir)/$(ruby_version)
vendordir = $(rubylibprefix)/vendor_ruby
sitearchdir = $(sitelibdir)/$(sitearch)
sitelibdir = $(sitedir)/$(ruby_version)
sitedir = $(rubylibprefix)/site_ruby
rubyarchdir = $(rubylibdir)/$(arch)
rubylibdir = $(rubylibprefix)/$(ruby_version)
sitearchincludedir = $(includedir)/$(sitearch)
archincludedir = $(includedir)/$(arch)
sitearchlibdir = $(libdir)/$(sitearch)
archlibdir = $(libdir)/$(arch)
ridir = $(datarootdir)/$(RI_BASE_NAME)
mandir = $(datarootdir)/man
localedir = $(datarootdir)/locale
libdir = $(exec_prefix)/lib
psdir = $(docdir)
pdfdir = $(docdir)
dvidir = $(docdir)
htmldir = $(docdir)
infodir = $(datarootdir)/info
docdir = $(datarootdir)/doc/$(PACKAGE)
oldincludedir = $(DESTDIR)/usr/include
includedir = $(prefix)/include
runstatedir = $(localstatedir)/run
localstatedir = $(prefix)/var
sharedstatedir = $(prefix)/com
sysconfdir = $(prefix)/etc
datadir = $(datarootdir)
datarootdir = $(prefix)/share
libexecdir = $(exec_prefix)/libexec
sbindir = $(exec_prefix)/sbin
bindir = $(exec_prefix)/bin
archdir = $(rubyarchdir)


CC_WRAPPER = 
CC = gcc
CXX = g++
LIBRUBY = $(LIBRUBY_SO)
LIBRUBY_A = lib$(RUBY_SO_NAME)-static.a
LIBRUBYARG_SHARED = -Wl,-rpath,$(libdir) -L$(libdir) -l$(RUBY_SO_NAME)
LIBRUBYARG_STATIC = -Wl,-rpath,$(libdir) -L$(libdir) -l$(RUBY_SO_NAME)-static $(MAINLIBS)
empty =
OUTFLAG = -o $(empty)
COUTFLAG = -o $(empty)
CSRCFLAG = $(empty)

RUBY_EXTCONF_H = 
cflags   = $(optflags) $(debugflags) $(warnflags)
cxxflags = 
optflags = -O3 -fno-fast-math
debugflags = -ggdb3
warnflags = -Wall -Wextra -Wdeprecated-declarations -Wdiv-by-zero -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wpointer-arith -Wwrite-strings -Wold-style-definition -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable -Wmisleading-indentation -Wundef
cppflags = 
CCDLFLAGS = -fPIC
CFLAGS   = $(CCDLFLAGS) $(cflags)  -fPIC $(ARCH_FLAG)
INCFLAGS = -I. -I$(arch_hdrdir) -I$(hdrdir)/ruby/backward -I$(hdrdir) -I$(srcdir)
DEFS     = 
CPPFLAGS =   $(DEFS) $(cppflags)
CXXFLAGS = $(CCDLFLAGS)  $(ARCH_FLAG)
ldflags  = -L. -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,--no-as-needed
dldflags = -Wl,--compress-debug-sections=zlib 
ARCH_FLAG = 
DLDFLAGS = $(ldflags) $(dldflags) $(ARCH_FLAG)
LDSHARED = $(CC) -shared
LDSHAREDXX = $(CXX) -shared
AR = gcc-ar
EXEEXT = 

RUBY_INSTALL_NAME = $(RUBY_BASE_NAME)
RUBY_SO_NAME = ruby
RUBYW_INSTALL_NAME = 
RUBY_VERSION_NAME = $(RUBY_BASE_NAME)-$(ruby_version)
RUBYW_BASE_NAME = rubyw
RUBY_BASE_NAME = ruby

arch = x86_64-linux
sitearch = $(arch)
ruby_version = 3.3.0
ruby = $(bindir)/$(RUBY_BASE_NAME)
RUBY = $(ruby)
BUILTRUBY = $(bindir)/$(RUBY_BASE_NAME)
ruby_headers = $(hdrdir)/ruby.h $(hdrdir)/ruby/backward.h $(hdrdir)/ruby/ruby.h $(hdrdir)/ruby/defines.h $(hdrdir)/ruby/missing.h $(hdrdir)/ruby/intern.h $(hdrdir)/ruby/st.h $(hdrdir)/ruby/subst.h $(arch_hdrdir)/ruby/config.h

RM = rm -f
RM_RF = rm -fr
RMDIRS = rmdir --ignore-fail-on-non-empty -p
MAKEDIRS = /usr/bin/mkdir -p
INSTALL = /usr/bin/install -c
INSTALL_PROG = $(INSTALL) -m 0755
INSTALL_DATA = $(INSTALL) -m 644
COPY = cp
TOUCH = exit >

#### End of system configuration section. ####

preload = 
libpath = . $(libdir)
LIBPATH =  -L. -L$(libdir) -Wl,-rpath,$(libdir)
DEFFILE = 

CLEANFILES = mkmf.log
DISTCLEANFILES = 
DISTCLEANDIRS = 

extout = 
extout_prefix = 
target_prefix = 
LOCAL_LIBS = 
LIBS = $(LIBRUBYARG_SHARED)  -lm -lpthread  -lc
ORIG_SRCS = 
SRCS = $(ORIG_SRCS) 
OBJS = 
HDRS = 
LOCAL_HDRS = 
TARGET = 
TARGET_NAME = 
TARGET_ENTRY = Init_$(TARGET_NAME)
DLLIB = 
EXTSTATIC = 
STATIC_LIB = 

TIMESTAMP_DIR = .
BINDIR        = $(bindir)
RUBYCOMMONDIR = $(sitedir)$(target_prefix)
RUBYLIBDIR    = $(sitelibdir)$(target_prefix)
RUBYARCHDIR   = $(sitearchdir)$(target_prefix)
HDRDIR        = $(sitehdrdir)$(target_prefix)
ARCHHDRDIR    = $(sitearchhdrdir)$(target_prefix)
TARGET_SO_DIR =
TARGET_SO     = $(TARGET_SO_DIR)$(DLLIB)
CLEANLIBS     = false
CLEANOBJS     = $(OBJS) *.bak
TARGET_SO_DIR_TIMESTAMP = $(TIMESTAMP_DIR)/.sitearchdir.time

all:    Makefile
static: $(STATIC_LIB)
.PHONY: all install static install-so install-rb
.PHONY: clean clean-so clean-static clean-rb

clean-static::
clean-rb-default::
clean-rb::
clean-so::
clean: clean-so clean-static clean-rb-default clean-rb
		-$(Q)$(RM_RF) $(CLEANLIBS) $(CLEANOBJS) $(CLEANFILES) .*.time

distclean-rb-default::
distclean-rb::
distclean-so::
distclean-static::
distclean: clean distclean-so distclean-static distclean-rb-default distclean-rb
		-$(Q)$(RM) Makefile $(RUBY_EXTCONF_H) conftest.* mkmf.log
		-$(Q)$(RM) core ruby$(EXEEXT) *~ $(DISTCLEANFILES)
		-$(Q)$(RMDIRS) $(DISTCLEANDIRS) 2> /dev/null || true

realclean: distclean
install: install-so install-rb

install-so: Makefile
install-rb: pre-install-rb do-install-rb install-rb-default
install-rb-default: pre-install-rb-default do-install-rb-default
pre-install-rb: Makefile
pre-install-rb-default: Makefile
do-install-rb:
do-install-rb-default:
pre-install-rb-default: $(TIMESTAMP_DIR)/.sitelibdir.time
do-install-rb-default: $(RUBYLIBDIR)/glib-mkenums.rb
$(RUBYLIBDIR)/glib-mkenums.rb: $(srcdir)/lib/glib-mkenums.rb $(TIMESTAMP_DIR)/.sitelibdir.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/glib-mkenums.rb $(@D)
do-install-rb-default: $(RUBYLIBDIR)/glib2.rb
$(RUBYLIBDIR)/glib2.rb: $(srcdir)/lib/glib2.rb $(TIMESTAMP_DIR)/.sitelibdir.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/glib2.rb $(@D)
do-install-rb-default: $(RUBYLIBDIR)/gnome2-raketask.rb
$(RUBYLIBDIR)/gnome2-raketask.rb: $(srcdir)/lib/gnome2-raketask.rb $(TIMESTAMP_DIR)/.sitelibdir.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/gnome2-raketask.rb $(@D)
do-install-rb-default: $(RUBYLIBDIR)/mkmf-gnome.rb
$(RUBYLIBDIR)/mkmf-gnome.rb: $(srcdir)/lib/mkmf-gnome.rb $(TIMESTAMP_DIR)/.sitelibdir.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/mkmf-gnome.rb $(@D)
do-install-rb-default: $(RUBYLIBDIR)/mkmf-gnome2.rb
$(RUBYLIBDIR)/mkmf-gnome2.rb: $(srcdir)/lib/mkmf-gnome2.rb $(TIMESTAMP_DIR)/.sitelibdir.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/mkmf-gnome2.rb $(@D)
pre-install-rb-default: $(TIMESTAMP_DIR)/.sitelibdir.-.glib2.time
do-install-rb-default: $(RUBYLIBDIR)/glib2/arg-info.rb
$(RUBYLIBDIR)/glib2/arg-info.rb: $(srcdir)/lib/glib2/arg-info.rb $(TIMESTAMP_DIR)/.sitelibdir.-.glib2.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/glib2/arg-info.rb $(@D)
do-install-rb-default: $(RUBYLIBDIR)/glib2/boxed-info.rb
$(RUBYLIBDIR)/glib2/boxed-info.rb: $(srcdir)/lib/glib2/boxed-info.rb $(TIMESTAMP_DIR)/.sitelibdir.-.glib2.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/glib2/boxed-info.rb $(@D)
do-install-rb-default: $(RUBYLIBDIR)/glib2/callable-info.rb
$(RUBYLIBDIR)/glib2/callable-info.rb: $(srcdir)/lib/glib2/callable-info.rb $(TIMESTAMP_DIR)/.sitelibdir.-.glib2.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/glib2/callable-info.rb $(@D)
do-install-rb-default: $(RUBYLIBDIR)/glib2/collection-reader.rb
$(RUBYLIBDIR)/glib2/collection-reader.rb: $(srcdir)/lib/glib2/collection-reader.rb $(TIMESTAMP_DIR)/.sitelibdir.-.glib2.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/glib2/collection-reader.rb $(@D)
do-install-rb-default: $(RUBYLIBDIR)/glib2/date-time.rb
$(RUBYLIBDIR)/glib2/date-time.rb: $(srcdir)/lib/glib2/date-time.rb $(TIMESTAMP_DIR)/.sitelibdir.-.glib2.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/glib2/date-time.rb $(@D)
do-install-rb-default: $(RUBYLIBDIR)/glib2/deprecatable.rb
$(RUBYLIBDIR)/glib2/deprecatable.rb: $(srcdir)/lib/glib2/deprecatable.rb $(TIMESTAMP_DIR)/.sitelibdir.-.glib2.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/glib2/deprecatable.rb $(@D)
do-install-rb-default: $(RUBYLIBDIR)/glib2/deprecated.rb
$(RUBYLIBDIR)/glib2/deprecated.rb: $(srcdir)/lib/glib2/deprecated.rb $(TIMESTAMP_DIR)/.sitelibdir.-.glib2.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/glib2/deprecated.rb $(@D)
do-install-rb-default: $(RUBYLIBDIR)/glib2/function-info.rb
$(RUBYLIBDIR)/glib2/function-info.rb: $(srcdir)/lib/glib2/function-info.rb $(TIMESTAMP_DIR)/.sitelibdir.-.glib2.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/glib2/function-info.rb $(@D)
do-install-rb-default: $(RUBYLIBDIR)/glib2/interface-info.rb
$(RUBYLIBDIR)/glib2/interface-info.rb: $(srcdir)/lib/glib2/interface-info.rb $(TIMESTAMP_DIR)/.sitelibdir.-.glib2.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/glib2/interface-info.rb $(@D)
do-install-rb-default: $(RUBYLIBDIR)/glib2/loader.rb
$(RUBYLIBDIR)/glib2/loader.rb: $(srcdir)/lib/glib2/loader.rb $(TIMESTAMP_DIR)/.sitelibdir.-.glib2.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/glib2/loader.rb $(@D)
do-install-rb-default: $(RUBYLIBDIR)/glib2/object-info.rb
$(RUBYLIBDIR)/glib2/object-info.rb: $(srcdir)/lib/glib2/object-info.rb $(TIMESTAMP_DIR)/.sitelibdir.-.glib2.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/glib2/object-info.rb $(@D)
do-install-rb-default: $(RUBYLIBDIR)/glib2/regex.rb
$(RUBYLIBDIR)/glib2/regex.rb: $(srcdir)/lib/glib2/regex.rb $(TIMESTAMP_DIR)/.sitelibdir.-.glib2.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/glib2/regex.rb $(@D)
do-install-rb-default: $(RUBYLIBDIR)/glib2/registered-type-info.rb
$(RUBYLIBDIR)/glib2/registered-type-info.rb: $(srcdir)/lib/glib2/registered-type-info.rb $(TIMESTAMP_DIR)/.sitelibdir.-.glib2.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/glib2/registered-type-info.rb $(@D)
do-install-rb-default: $(RUBYLIBDIR)/glib2/repository.rb
$(RUBYLIBDIR)/glib2/repository.rb: $(srcdir)/lib/glib2/repository.rb $(TIMESTAMP_DIR)/.sitelibdir.-.glib2.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/glib2/repository.rb $(@D)
do-install-rb-default: $(RUBYLIBDIR)/glib2/struct-info.rb
$(RUBYLIBDIR)/glib2/struct-info.rb: $(srcdir)/lib/glib2/struct-info.rb $(TIMESTAMP_DIR)/.sitelibdir.-.glib2.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/glib2/struct-info.rb $(@D)
do-install-rb-default: $(RUBYLIBDIR)/glib2/time-zone.rb
$(RUBYLIBDIR)/glib2/time-zone.rb: $(srcdir)/lib/glib2/time-zone.rb $(TIMESTAMP_DIR)/.sitelibdir.-.glib2.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/glib2/time-zone.rb $(@D)
do-install-rb-default: $(RUBYLIBDIR)/glib2/type-info.rb
$(RUBYLIBDIR)/glib2/type-info.rb: $(srcdir)/lib/glib2/type-info.rb $(TIMESTAMP_DIR)/.sitelibdir.-.glib2.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/glib2/type-info.rb $(@D)
do-install-rb-default: $(RUBYLIBDIR)/glib2/type-tag.rb
$(RUBYLIBDIR)/glib2/type-tag.rb: $(srcdir)/lib/glib2/type-tag.rb $(TIMESTAMP_DIR)/.sitelibdir.-.glib2.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/glib2/type-tag.rb $(@D)
do-install-rb-default: $(RUBYLIBDIR)/glib2/union-info.rb
$(RUBYLIBDIR)/glib2/union-info.rb: $(srcdir)/lib/glib2/union-info.rb $(TIMESTAMP_DIR)/.sitelibdir.-.glib2.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/glib2/union-info.rb $(@D)
do-install-rb-default: $(RUBYLIBDIR)/glib2/value.rb
$(RUBYLIBDIR)/glib2/value.rb: $(srcdir)/lib/glib2/value.rb $(TIMESTAMP_DIR)/.sitelibdir.-.glib2.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/glib2/value.rb $(@D)
do-install-rb-default: $(RUBYLIBDIR)/glib2/variant-type.rb
$(RUBYLIBDIR)/glib2/variant-type.rb: $(srcdir)/lib/glib2/variant-type.rb $(TIMESTAMP_DIR)/.sitelibdir.-.glib2.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/glib2/variant-type.rb $(@D)
do-install-rb-default: $(RUBYLIBDIR)/glib2/variant.rb
$(RUBYLIBDIR)/glib2/variant.rb: $(srcdir)/lib/glib2/variant.rb $(TIMESTAMP_DIR)/.sitelibdir.-.glib2.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/glib2/variant.rb $(@D)
do-install-rb-default: $(RUBYLIBDIR)/glib2/version.rb
$(RUBYLIBDIR)/glib2/version.rb: $(srcdir)/lib/glib2/version.rb $(TIMESTAMP_DIR)/.sitelibdir.-.glib2.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/glib2/version.rb $(@D)
pre-install-rb-default: $(TIMESTAMP_DIR)/.sitelibdir.-.gnome.-.rake.time
do-install-rb-default: $(RUBYLIBDIR)/gnome/rake/external-package.rb
$(RUBYLIBDIR)/gnome/rake/external-package.rb: $(srcdir)/lib/gnome/rake/external-package.rb $(TIMESTAMP_DIR)/.sitelibdir.-.gnome.-.rake.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/gnome/rake/external-package.rb $(@D)
do-install-rb-default: $(RUBYLIBDIR)/gnome/rake/native-binary-build-task.rb
$(RUBYLIBDIR)/gnome/rake/native-binary-build-task.rb: $(srcdir)/lib/gnome/rake/native-binary-build-task.rb $(TIMESTAMP_DIR)/.sitelibdir.-.gnome.-.rake.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/gnome/rake/native-binary-build-task.rb $(@D)
do-install-rb-default: $(RUBYLIBDIR)/gnome/rake/package-task.rb
$(RUBYLIBDIR)/gnome/rake/package-task.rb: $(srcdir)/lib/gnome/rake/package-task.rb $(TIMESTAMP_DIR)/.sitelibdir.-.gnome.-.rake.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/gnome/rake/package-task.rb $(@D)
do-install-rb-default: $(RUBYLIBDIR)/gnome/rake/package.rb
$(RUBYLIBDIR)/gnome/rake/package.rb: $(srcdir)/lib/gnome/rake/package.rb $(TIMESTAMP_DIR)/.sitelibdir.-.gnome.-.rake.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/gnome/rake/package.rb $(@D)
do-install-rb-default: $(RUBYLIBDIR)/gnome/rake/source-download-task.rb
$(RUBYLIBDIR)/gnome/rake/source-download-task.rb: $(srcdir)/lib/gnome/rake/source-download-task.rb $(TIMESTAMP_DIR)/.sitelibdir.-.gnome.-.rake.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/gnome/rake/source-download-task.rb $(@D)
do-install-rb-default: $(RUBYLIBDIR)/gnome/rake/windows-binary-build-task.rb
$(RUBYLIBDIR)/gnome/rake/windows-binary-build-task.rb: $(srcdir)/lib/gnome/rake/windows-binary-build-task.rb $(TIMESTAMP_DIR)/.sitelibdir.-.gnome.-.rake.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/gnome/rake/windows-binary-build-task.rb $(@D)
do-install-rb-default: $(RUBYLIBDIR)/gnome/rake/windows-binary-download-task.rb
$(RUBYLIBDIR)/gnome/rake/windows-binary-download-task.rb: $(srcdir)/lib/gnome/rake/windows-binary-download-task.rb $(TIMESTAMP_DIR)/.sitelibdir.-.gnome.-.rake.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/gnome/rake/windows-binary-download-task.rb $(@D)
pre-install-rb-default: $(TIMESTAMP_DIR)/.sitelibdir.-.gnome2.-.rake.time
do-install-rb-default: $(RUBYLIBDIR)/gnome2/rake/package-task.rb
$(RUBYLIBDIR)/gnome2/rake/package-task.rb: $(srcdir)/lib/gnome2/rake/package-task.rb $(TIMESTAMP_DIR)/.sitelibdir.-.gnome2.-.rake.time
	$(Q) $(INSTALL_DATA) $(srcdir)/lib/gnome2/rake/package-task.rb $(@D)
pre-install-rb-default:
	$(Q1:0=@$(MAKE) -q do-install-rb-default || )$(ECHO1:0=echo) installing default  libraries
$(TIMESTAMP_DIR)/.sitelibdir.time:
	$(Q) $(MAKEDIRS) $(@D) $(RUBYLIBDIR)
	$(Q) $(TOUCH) $@
$(TIMESTAMP_DIR)/.sitelibdir.-.glib2.time:
	$(Q) $(MAKEDIRS) $(@D) $(RUBYLIBDIR)/glib2
	$(Q) $(TOUCH) $@
$(TIMESTAMP_DIR)/.sitelibdir.-.gnome.-.rake.time:
	$(Q) $(MAKEDIRS) $(@D) $(RUBYLIBDIR)/gnome/rake
	$(Q) $(TOUCH) $@
$(TIMESTAMP_DIR)/.sitelibdir.-.gnome2.-.rake.time:
	$(Q) $(MAKEDIRS) $(@D) $(RUBYLIBDIR)/gnome2/rake
	$(Q) $(TOUCH) $@

site-install: site-install-so site-install-rb
site-install-so: install-so
site-install-rb: install-rb

