# -*- ruby -*-
#
# Copyright (C) 2010-2018  Ruby-GNOME2 Project Team
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

$LOAD_PATH.unshift("./../glib2/lib")
require 'gnome2-raketask'

package_name = File.basename(__dir__)
spec = Gem::Specification.load("#{package_name}.gemspec")

GNOME2::Rake::PackageTask.define(spec, __dir__) do |package|
  package.windows.packages = []
  package.windows.dependencies = []
  package.windows.build_dependencies = [
    "glib2",
    "gobject-introspection",
    "gio2",
    "cairo-gobject",
  ]
  package.windows.gobject_introspection_dependencies = [
    "gio2",
    "cairo-gobject",
  ]
  package.external_packages = [
    {
      :name => "libjpeg",
      :base_name => "jpeg-9b",
      :archive_base_name => "jpegsrc.v9b.tar.gz",
      :download_base_url => "http://www.ijg.org/files",
      :label => "libjpeg",
      :windows => {
        :configure_args => [],
        :built_file => "bin/libjpeg-9.dll",
      },
    },
    {
      :name => "sqlite-autoconf",
      :download_base_url => "http://www.sqlite.org/2016",
      :label => "SQLite",
      :version => "3140100",
      :compression_method => "gz",
      :windows => {
        :configure_args => [],
        :built_file => "bin/libsqlite3-0.dll",
      },
    },
    {
      :name => "openjpeg",
      :base_name => "openjpeg-version.2.1",
      :archive_base_name => "version.2.1.tar.gz",
      :download_base_url => "https://github.com/uclouvain/openjpeg/archive",
      :label => "OpenJPEG",
      :windows => {
        :cmake_args => [
          "-DBUILD_PKGCONFIG_FILES=on",
        ],
        :built_file => "bin/libopenjp2.dll",
      },
    },
    {
      :name => "poppler",
      :download_base_url => "https://poppler.freedesktop.org",
      :label => "Poppler",
      :version => "0.42.0",
      :compression_method => "xz",
      :windows => {
        :configure_args => [
          "--enable-zlib",
          "--enable-introspection",
        ],
        :built_file => "bin/libpoppler-glib-8.dll",
      },
    },
  ]
end
