# -*- ruby -*-

require './../glib2/lib/gnome2-raketask'

package = GNOME2Package.new do |_package|
  _package.summary = "Ruby/Poppler is a Ruby binding of poppler-glib."
  _package.description = "Ruby/Poppler is a Ruby binding of poppler-glib."
  _package.dependency.gem.runtime = ["gtk2"]
  _package.win32.packages = []
  _package.win32.dependencies = ["poppler",
                                 ["libpng", "1.2.40-1"],
                                 ["jpeg", "7-1"]]
end
package.define_tasks

