# -*- ruby -*-

$LOAD_PATH.unshift("./../glib2/lib")
require 'gnome2/rake/package-task'

package_task = GNOME2::Rake::PackageTask.new do |package|
  package.summary = "Ruby/VTE is a Ruby binding of VTE."
  package.description = "Ruby/VTE is a Ruby binding of VTE."
  package.dependency.gem.runtime = ["gtk3", "gobject-introspection"]
  package.windows.packages = []
  package.windows.dependencies = []
  package.windows.build_dependencies = [
    "glib2", "atk", "pango", "gdk_pixbuf2", "gdk3",
  ]
  package.windows.build_packages = [
    # {
    #   :name => "ncurses",
    #   :download_base_url => "http://ftp.gnu.org/pub/gnu/ncurses",
    #   :label => "ncurses",
    #   :version => "5.9",
    #   :configure_args => [
    #     "--enable-sp-funcs",
    #     "--enable-term-driver",
    #     "--with-shared",
    #     "--without-normal",
    #     "--without-progs",
    #     "--without-tests",
    #   ],
    #   :patches => [
    #     "ncurses-5.9-support-mingw32.diff",
    #     "ncurses-5.9-add-missing-exe.diff",
    #   ],
    # },
    # {
    #   :name => "vte",
    #   :download_site => :gnome,
    #   :label => "vte",
    #   :version => "0.34.2",
    #   :configure_args => [],
    #   :compression_method => "xz",
    # }
  ]
  package.post_install_message = "This library is experimental."
end
package_task.define
