# -*- ruby -*-
#
# Copyright (C) 2013-2014  Ruby-GNOME2 Project Team
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

$LOAD_PATH.unshift("./../glib2/lib")
require "gnome2/rake/package-task"

package_task = GNOME2::Rake::PackageTask.new do |package|
  package.summary = "Ruby/ClutterGStreamer is a Ruby binding of Clutter-GStreamer."
  package.description = "Ruby/ClutterGStreamer is a Ruby binding of Clutter-GStreamer."
  package.dependency.gem.runtime = ["clutter", "gstreamer"]
  package.dependency.gem.development = ["test-unit-notify"]
  package.windows.packages = []
  package.windows.dependencies = []
  package.windows.build_dependencies = [
    "glib2",
    "gdk_pixbuf2",
    "atk",
    "pango",
    "gobject-introspection",
    "clutter",
    "gstreamer",
  ]
  package.windows.gobject_introspection_dependencies = [
    "atk",
    "pango",
    "clutter",
    "gstreamer",
  ]
  package.external_packages = [
    {
      :name => "clutter-gst",
      :download_site => :gnome,
      :label => "Clutter-GStreamer",
      :version => "2.0.12",
      :compression_method => "xz",
      :windows => {
        :configure_args => [
          "--enable-introspection",
        ],
        :built_file => "bin/libclutter-gst-2.0-0.dll",
      },
    }
  ]
end
package_task.define

Rake::Task["native:clutter-gstreamer:i386-mingw32"].prerequisites.clear

namespace :dependency do
  desc "Install depenencies"
  task :install do
    # TODO: Install gir1.2-clutter-gst-1.0 on Debian.
  end
end

task :build => "dependency:install"
