# -*- ruby -*-

$LOAD_PATH.unshift("./../glib2/lib")
require 'gnome2-raketask'

package = GNOME2Package.new do |_package|
  _package.summary = "Ruby/VTE is a Ruby binding of VTE."
  _package.description = "Ruby/VTE is a Ruby binding of VTE."
  _package.dependency.gem.runtime = ["gtk3"]
  _package.win32.packages = []
  _package.win32.dependencies = []
  _package.required_ruby_version = ">= 1.9.2"
  _package.post_install_message = "This library is experimental."
end
package.define_tasks

